version: "3.4"

services:
  archival:
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes: ["./src:/src"]
    ports: [7000:80]
    env_file: .env
    environment:
      PORT: 80
      LOG_LEVEL: DEBUG
      GUNICORN_reload: "True"
